Refactoring and added option to disable color

diff --git a/pbfetch b/pbfetch
--- a/pbfetch
+++ b/pbfetch
@@ -4,54 +4,80 @@
 # aurget: http://pbrisbin.com:8080/pages/aurget.html #
 ######################################################
 
-NAME="pbfetch"
-VERSION="v0.3"
-DESCRIPTION="Simple script to fetch PKGBUILDS from AUR & ABS"
-AUTHOR="-Erik Hardesty"
-DATE="(12/13/09)"
+name="pbfetch"
+version="v0.35"
+description="Simple script to fetch PKGBUILDS from aur & abs"
+author="-Erik Hardesty"
+date="(12/13/09)"
 
-#PKGBUILD EDITOR
-EDITOR="vim"
+######################################################
+#################### User Settings ###################
+######################################################
+
+#Colorize output
+color=true
+
+#PKGBUILD editor
+editor="vim"
 
 #BUILD DIRECTORY
-BUILDDIR=~/build
+buildDir=~/build
 
-#LOCAL ABS DIRECTORY
-ABS="/var/abs"
+#LOCAL abs DIRECTORY
+abs="/var/abs"
 
-#AUR URL
-AUR="http://aur.archlinux.org/packages"
+#aur URL
+aur="http://aur.archlinux.org/packages"
+
+######################################################
+################## End User Settings #################
+######################################################
+
 
 #COLORS
-BOLD=$(tput bold)
-RESET=$(tput sgr0)
-colorW="[1;37m" # white
-colorB="[1;34m" # blue
-colorR="[1;31m" # red
-colorG="[1;32m" # green
-colorY="[1;33m" # yellow
-colorM="[1;35m" # magenta
+if $color; then
+    bold=$(tput bold)
+    reset=$(tput sgr0)
+    colorW="\e[1;37m" # white
+    colorB="\e[1;34m" # blue
+    colorR="\e[1;31m" # red
+    colorG="\e[1;32m" # green
+    colorY="\e[1;33m" # yellow
+    colorM="\e[1;35m" # magenta
+else
+    bold=''
+    reset=''
+    colorW=''
+    colorB=''
+    colorR=''
+    colorG=''
+    colorY=''
+    colorM=''
+fi
+
 
 #OUTPUT SHORTCUTS
-LEFTB="$BOLD\e$colorB["
-RIGHTB="$BOLD\e$colorB]"
-MARKER="$BOLD\e$colorG:: "
-EXT="${LEFTB}\e${colorG}Extracted${RIGHTB}${RESET}"
-DOWNL="${LEFTB}\e${colorG}Downloaded${RIGHTB}${RESET}"
-COPIED="${LEFTB}\e${colorG}Copied${RIGHTB}${RESET}"
-DFAIL="$LEFTB\e${colorR}DOWNLOAD FAILED$RIGHTB$RESET"
-CFAIL="$LEFTB\e${colorR}CLEAN UP FAILED$RIGHTB$RESET"
-NFOUND="$LEFTB\e${colorR}NOT FOUND$RIGHTB$RESET"
-INSTALLED="${LEFTB}\e${colorW}INSTALLED${RIGHTB}${RESET}"
+leftB="$bold$colorB["
+rightB="$bold$colorB]"
+marker="$bold$colorG:: "
+ext="${leftB}${colorG}Extracted${rightB}${reset}"
+downl="${leftB}${colorG}Downloaded${rightB}${reset}"
+copied="${leftB}${colorG}Copied${rightB}${reset}"
+dFail="$leftB${colorR}downlOAD FAILED$rightB$reset"
+cFail="$leftB${colorR}CLEAN UP FAILED$rightB$reset"
+nFound="$leftB${colorR}NOT FOUND$rightB$reset"
+installed="${leftB}${colorW}installed${rightB}${reset}"
 
 #WORKING GLOBAL VARIABLES
-PKGNAME="" 
-PKGVERSION=""
-PKGRELEASE=""
-declare -a PKGUPGRADES
+pkgName="" 
+pkgVersion=""
+pkgRelease=""
+declare -a pkgUpgrades
 declare -a selectedUpdates
-UPGRADEINDX=0
-FORCE=true
+upgradeIndx=0
+force=true
+edit=false
+installPkg=false
 
 
 
@@ -62,12 +88,12 @@ FORCE=true
 ##### FUNCTIONS #####
 #####################
 cleanExit() {
-    rm $BUILDDIR/results.lst
+    rm $buildDir/results.lst
     exit
 }
 
 error() {
-    echo -e "$MARKER$1 ${RESET}"
+    echo -e "$marker$1 ${reset}"
     exit
 }
 
@@ -75,28 +101,28 @@ checkInstall() {
     pacman -Qq $1 &>/dev/null    
 }
 
-searchAUR() {
+SearchAur() {
 
-    touch $BUILDDIR/results.lst
+    touch $buildDir/results.lst
 
   for term in $@; do
-    curl -s "http://aur.archlinux.org/rpc.php?type=search&arg=${term}" | sed 's/{/\n/g' | grep $term >> $BUILDDIR/results.lst
+    curl -s "http://aur.archlinux.org/rpc.php?type=search&arg=${term}" | sed 's/{/\n/g' | grep $term >> $buildDir/results.lst
   done
 
-  [ ! -s $BUILDDIR/results.lst ] && exit
+  [ ! -s $buildDir/results.lst ] && exit
 
-  sort $BUILDDIR/results.lst | uniq | while read line; do
+  sort $buildDir/results.lst | uniq | while read line; do
     name="$(echo $line | awk -F '"' '{print $8}')"
     vers="$(echo $line | awk -F '"' '{print $12}')"
     desc="$(echo $line | awk -F '"' '{print $20}')"
     flag="$(echo $line | awk -F '"' '{print $44}')"
 
-    echo -e -n "\e${colorM}aur/\e${colorW}$name \e${colorG}$vers\e[0m"
-    [ "$flag" = "1" -o "$flag" = "OutOfDate" ] && echo -e -n " \e${colorR}[out of date]\e[0m"
+    echo -e -n "${colorM}aur/${colorW}$name ${colorG}$vers${bold}"
+    [ "$flag" = "1" -o "$flag" = "OutOfDate" ] && echo -e -n " ${colorR}[out of date]${bold}"
 
     if checkInstall "$name";
     then
-	echo -e -n " $INSTALLED"
+	echo -e -n " $installed"
     fi
 
     echo -e "\n    $desc"
@@ -106,22 +132,19 @@ searchAUR() {
   cleanExit
 }
 
-downloadAUR() {
-    cd $BUILDDIR || error "$LEFTB${colorR}Build directory does not exist$RIGHTB"
-    
-    EDIT=$1
-    shift
+DownloadAur() {
+    cd $buildDir || error "$leftB${colorR}Build directory does not exist$rightB"
 
     for i in "$@"
     do
-	wget -q ${AUR}/$i/$i.tar.gz || error "\e$colorW$i $DFAIL$RESET"
-        echo -e "$MARKER\e$colorW$i $DOWNL" 
+	wget -q ${aur}/$i/$i.tar.gz || error "$colorW$i $dFail$reset"
+        echo -e "$marker$colorW$i $downl" 
 
-	bsdtar -x -f $i.tar.gz && echo -e "$MARKER\e$colorW$i $EXT"
-        rm $i.tar.gz || error "${CFAIL}"
-	if $EDIT ; then
+	bsdtar -x -f $i.tar.gz && echo -e "$marker$colorW$i $ext"
+        rm $i.tar.gz || error "${cFail}"
+	if $edit ; then
 	    editPB $i
-	    echo -e "$MARKER\e$colorW$i ${LEFTB}\e${colorB}\e${colorG}Edit complete${RIGHTB}"
+	    echo -e "$marker$colorW$i ${leftB}${colorB}${colorG}Edit complete${rightB}"
 	fi
     done
 
@@ -130,163 +153,159 @@ downloadAUR() {
 editPB() {
     if [ -e $1/PKGBUILD ]
     then
-	$EDITOR $BUILDDIR/$1/PKGBUILD
+	$editor $buildDir/$1/PKGBUILD
     else
-	echo -e "\e${colorR}${BOLD}Error: \e${colorW}Could not open PKGBUILD!${RESET}"
+	echo -e "${colorR}${bold}Error: ${colorW}Could not open PKGBUILD!${reset}"
     fi
 }
 
-copyABS() {
+CopyAbs() {
     for i in "$@"
     do
-	cp -r `find /var/abs -name "$i"` $BUILDDIR || error "\e$colorW$i $NFOUND"
-	echo -e "$MARKER\e$colorW$i $COPIED"
+	cp -r `find /var/abs -name "$i"` $buildDir || error "$colorW$i $nFound"
+	echo -e "$marker$colorW$i $copied"
     done
 }
 
-makePackages() {
-
-    #Store install flag
-    INSTALL=$1
-    shift
+MakePackages() {
 
     for i in "$@"
     do
-	if [ -e $BUILDDIR/$i/PKGBUILD ]
+	if [ -e $buildDir/$i/PKGBUILD ]
 	then
-	    cd $BUILDDIR/$i
-	    if $INSTALL; then
-		if $FORCE; then
+	    cd $buildDir/$i
+	    if $installPkg; then
+		if $force; then
 		    makepkg -fsi
 		else
 		    makepkg -si
 		fi
-	    elif $FORCE; then
+	    elif $force; then
 		makepkg -fs
 	    else
 		makepkg -s
 	    fi
 	else
-	    echo -e "\e${colorR}${BOLD}Error: \e${colorW}Could not open PKGBUILD!${RESET}"
+	    echo -e "${colorR}${bold}Error: ${colorW}Could not open PKGBUILD!${reset}"
 	fi
     done
 
 }
 
 checkVersion () {   
-    TEMP="$(curl -s "http://aur.archlinux.org/rpc.php?type=info&arg=$PKGNAME" | awk -F '"' '{print $18}')"
-    AURVERSION="$(echo $TEMP | awk -F "-" '{print $1}')"
-    AURRELEASE="$(echo $TEMP | awk -F "-" '{print $2}')"
+    TEMP="$(curl -s "http://aur.archlinux.org/rpc.php?type=info&arg=$pkgName" | awk -F '"' '{print $18}')"
+    aurversion="$(echo $TEMP | awk -F "-" '{print $1}')"
+    aurRELEASE="$(echo $TEMP | awk -F "-" '{print $2}')"
 
-    if [ "$AURVERSION" \> "$PKGVERSION" ]; then
-	UPGRADE="\e${colorG}Update Available"
-	echo $PKGNAME >> $BUILDDIR/upgrades.txt
-    elif [[ "$AURVERSION" = "$PKGVERSION" && "$AURRELEASE" > "$PKGRELEASE" ]]; then
-	UPGRADE="\e${colorG}Update Available"
-	echo $PKGNAME >> $BUILDDIR/upgrades.txt
-    elif [ "$AURVERSION" == "" ]; then
-	UPGRADE="\e${colorY}Not found on AUR"
+    if [ "$aurversion" \> "$pkgVersion" ]; then
+	UPGRADE="${colorG}Update Available"
+	echo $pkgName >> $buildDir/upgrades.txt
+    elif [[ "$aurversion" = "$pkgVersion" && "$aurRELEASE" > "$pkgRelease" ]]; then
+	UPGRADE="${colorG}Update Available"
+	echo $pkgName >> $buildDir/upgrades.txt
+    elif [ "$aurversion" == "" ]; then
+	UPGRADE="${colorY}Not found on aur"
     else
-	UPGRADE="\e${colorB}Up to date"
+	UPGRADE="${colorB}Up to date"
     fi
 	    
-    echo -e "$PKGNAME $PKGVERSION-$PKGRELEASE \e${colorW}$AURVERSION-$AURRELEASE $UPGRADE${RESET}"
+    echo -e "$pkgName $pkgVersion-$pkgRelease ${colorW}$aurversion-$aurRELEASE $UPGRADE${reset}"
 
 }
 
 
-UpgradeAUR() {
-    echo -e "Checking AUR for package updates..."
+UpgradeAur() {
+    echo -e "Checking aur for package updates..."
     
-    pacman -Qm | sort > $BUILDDIR/localList.txt
+    pacman -Qm | sort > $buildDir/localList.txt
 
     while read line; do
-	PKGNAME="$(echo $line | awk -F " " '{print $1}')"
-	PKGVERSION="$(echo $line | awk -F " " '{print $2}' | awk -F "-" '{print $1}')"
-	PKGRELEASE="$(echo $line | awk -F " " '{print $2}' | awk -F "-" '{print $2}')"
+	pkgName="$(echo $line | awk -F " " '{print $1}')"
+	pkgVersion="$(echo $line | awk -F " " '{print $2}' | awk -F "-" '{print $1}')"
+	pkgRelease="$(echo $line | awk -F " " '{print $2}' | awk -F "-" '{print $2}')"
 	checkVersion&
-    done < $BUILDDIR/localList.txt
+    done < $buildDir/localList.txt
     wait
     
     while read line; do
-	PKGUPGRADES[UPGRADEINDX]=$line
-	((UPGRADEINDX++))
-    done < $BUILDDIR/upgrades.txt
-    rm $BUILDDIR/upgrades.txt
+	pkgUpgrades[upgradeIndx]=$line
+	((upgradeIndx++))
+    done < $buildDir/upgrades.txt
+    rm $buildDir/upgrades.txt
 
     
     echo
-    for ((i = 0; i<$UPGRADEINDX; i++))
+    for ((i = 0; i<$upgradeIndx; i++))
     do
-	echo -e -n "\e${colorG}$i${RESET}:\e${colorY}${PKGUPGRADES[$i]} ${RESET}| "
+	echo -e -n "${colorG}$i${reset}:${colorY}${pkgUpgrades[$i]} ${reset}| "
     done
 
-    echo -e "\n\e${colorB}------------------------------------------------------------------${RESET}"
+    echo -e "\n${colorB}------------------------------------------------------------------${reset}"
 
-    echo -e "\e${colorW}Do you want to update these packages?"
-    echo -e "\e${colorW}Press \e${colorG}Y \e${colorW}to update all, \e${colorG} C\e${colorW} to choose which to update: [Y/n/c]${RESET}"
+    echo -e "${colorW}Do you want to update these packages?"
+    echo -e "${colorW}Press ${colorG}Y ${colorW}to update all, ${colorG} C${colorW} to choose which to update: [Y/n/c]${reset}"
 
     while true; do
 	read ync
 	case $ync in
 	    [Yy]* ) 
-		FORCE=true
-		downloadAUR $1 ${PKGUPGRADES[@]}
-		makePackages true ${PKGUPGRADES[@]}
+		force=true
+		DownloadAur ${pkgUpgrades[@]}
+		MakePackages ${pkgUpgrades[@]}
 	       	break;;
 	    [Nn]* ) break;;
 	    [Cc]* )
-		FORCE=true
+		force=true
 	        echo -n "Enter the number of the corresponding package(s) (separate numbers by space)"	
 		read choices
 		prepSelectedArray "$choices"
-		downloadAUR $1 ${selectedUpdates[@]}
-		makePackages true ${selectedUpdates[@]}
+		DownloadAur ${selectedUpdates[@]}
+		MakePackages ${selectedUpdates[@]}
 		break;
 		;;
 	    *) 
-		FORCE=true
-		downloadAUR $1 ${PKGUPGRADES[@]}
-		makePackages true ${PKGUPGRADES[@]}
+		force=true
+		DownloadAur ${pkgUpgrades[@]}
+		MakePackages ${pkgUpgrades[@]}
 		;;
 	esac
     done
 
 
-    rm $BUILDDIR/localList.txt
+    rm $buildDir/localList.txt
 }
 
 prepSelectedArray() {
     arrayI=( $1 )
     indx=0
     for i in ${arrayI[@]}; do
-	selectedUpdates[indx]=${PKGUPGRADES[$i]}
+	selectedUpdates[indx]=${pkgUpgrades[$i]}
 	((indx++))
     done
 }
 
 
-usage() {
+Usage() {
     echo -e "Usage: pbfetch [opiton] [package1] [package2] ....\n"
     echo -e "    options:"
-    echo -e "        -d  Download from AUR and extract to build directory"
-    echo -e "        -de Download from AUR, extract and edit PKGBUILD"
-    echo -e "        -m  Download from AUR, extract, and make the package(s)"
-    echo -e "        -me Download from AUR, extract, edit PKGBUILD and make the package(s)"
-    echo -e "        -i  Download from AUR, extract, make and install package(s)"
-    echo -e "        -ie Download from AUR, extract, edit PKGBUILD, make and install package(s)"
-    echo -e "        -s  Search AUR for any package given (Searches name and description)"
-    echo -e "        -u  Check AUR for package updates"
-    echo -e "        -ue Check AUR for package updates and edit PKGBUILD before install"
+    echo -e "        -d  Download from aur and extract to build directory"
+    echo -e "        -de Download from aur, extract and edit PKGBUILD"
+    echo -e "        -m  Download from aur, extract, and make the package(s)"
+    echo -e "        -me Download from aur, extract, edit PKGBUILD and make the package(s)"
+    echo -e "        -i  Download from aur, extract, make and install package(s)"
+    echo -e "        -ie Download from aur, extract, edit PKGBUILD, make and install package(s)"
+    echo -e "        -s  Search aur for any package given (Searches name and description)"
+    echo -e "        -u  Check aur for package updates"
+    echo -e "        -ue Check aur for package updates and edit PKGBUILD before install"
     echo -e "        -abs Copy from local abs folder to build directory\n"
     echo -e "        -v  Display version information"
     echo -e "Example: pbfetch -d nvidia-beta nvidia-utils-beta\n"
 }
 
 version() {
-    echo -e "\n    \e${colorW}$NAME \e${colorG}$VERSION"
-    echo -e "    ${RESET}$DESCRIPTION"
-    echo -e "    \e${colorW}$AUTHOR \e${colorG}$DATE${RESET}\n"
+    echo -e "\n    ${colorW}$name ${colorG}$version"
+    echo -e "    ${reset}$description"
+    echo -e "    ${colorW}$author ${colorG}$date${reset}\n"
 }
 
 
@@ -297,54 +316,64 @@ version() {
 case $1 in
 -s)
     shift
-    searchAUR $@
+    pacman-color -Ss $@
+    SearchAur $@
     ;;
 -abs)
     shift
-    copyABS $@
+    CopyAbs $@
     ;;
 -d)
     shift
-    downloadAUR false $@
+    DownloadAur $@
     ;;
 -de)
     shift
-    downloadAUR true $@
+    edit=true
+    DownloadAur $@
     ;;
 -m)
     shift
-    downloadAUR false $@
-    makePackages false $@
+    DownloadAur $@
+    MakePackages $@
     ;;
 -me)
     shift
-    downloadAUR true $@
-    makePackages false $@
+    edit=true
+    DownloadAur $@
+    MakePackages $@
     ;;
 -i)
     shift
-    downloadAUR false $@
-    makePackages true $@
+    installPkg=true
+    DownloadAur $@
+    MakePackages $@
     ;;
 -ie)
     shift
-    downloadAUR true $@
-    makePackages true $@
+    installPkg=true
+    edit=true
+    DownloadAur $@
+    MakePackages $@
     ;;
 -u)
-    UpgradeAUR false
+    installPkg=true
+    UpgradeAur
     ;;
 -ue)
-    UpgradeAUR true
+    edit=true
+    installPkg=true
+    UpgradeAur
     ;;
 -ua)
+    installPkg=true
     sudo pacman -Syu
-    UpgradeAUR false
+    UpgradeAur
     ;;
 -v)
     version
     ;;
 *)
-    usage $1
+    Usage $1
 esac
 
